global using DynamicPLCDataCollector;
global using DynamicPLCDataCollector.Models;
global using DynamicPLCDataCollector.Services.DataStorages;
global using DynamicPLCDataCollector.Services.PLCClients;